A Projection Process

In [54]:
using LinearAlgebra, Combinatorics

In [55]:
N,n = 8,5
Y,_ = qr(randn(N,n))
Y = Matrix(Y)
L = Y*Y'

8×8 Array{Float64,2}:
  0.230107     0.206909   -0.0518406   …   0.170916  -0.200183    0.0461474
  0.206909     0.70726     0.118557        0.149166   0.109244   -0.0558501
 -0.0518406    0.118557    0.947277       -0.104955  -0.0155702   0.016098 
 -0.245416    -0.0787011   0.00742649     -0.220986   0.260469   -0.0920164
  0.00385185  -0.326617    0.147064        0.298237   0.0541379  -0.0535354
  0.170916     0.149166   -0.104955    …   0.50093    0.220162   -0.03563  
 -0.200183     0.109244   -0.0155702       0.220162   0.772014    0.0671691
  0.0461474   -0.0558501   0.016098       -0.03563    0.0671691   0.976841 

In [56]:
# All combinations of n subsets of 1:n
[𝓘 for 𝓘 ∈ combinations(1:N,n)]

56-element Array{Array{Int64,1},1}:
 [1, 2, 3, 4, 5]
 [1, 2, 3, 4, 6]
 [1, 2, 3, 4, 7]
 [1, 2, 3, 4, 8]
 [1, 2, 3, 5, 6]
 [1, 2, 3, 5, 7]
 [1, 2, 3, 5, 8]
 [1, 2, 3, 6, 7]
 [1, 2, 3, 6, 8]
 [1, 2, 3, 7, 8]
 [1, 2, 4, 5, 6]
 [1, 2, 4, 5, 7]
 [1, 2, 4, 5, 8]
 ⋮              
 [2, 3, 6, 7, 8]
 [2, 4, 5, 6, 7]
 [2, 4, 5, 6, 8]
 [2, 4, 5, 7, 8]
 [2, 4, 6, 7, 8]
 [2, 5, 6, 7, 8]
 [3, 4, 5, 6, 7]
 [3, 4, 5, 6, 8]
 [3, 4, 5, 7, 8]
 [3, 4, 6, 7, 8]
 [3, 5, 6, 7, 8]
 [4, 5, 6, 7, 8]

## This is a probability space

specifically P(𝓘) = det(K[𝓘,𝓘]) is thought of as the probability of 𝓘 

This is an n-DPP because all the points are size n

In [53]:
sum(det(K[𝓘,𝓘]) for 𝓘 ∈ combinations(1:N,n) )

0.24999999999999992

## if you take sizes k smaller than p you need to correct with binomial(p,j)

In [57]:
[[sum(det(L[𝒬,𝒬]) for 𝒬 ∈ combinations(1:N,k) ) for k=0:n] [binomial(n,k) for k=0:n]]

6×2 Array{Float64,2}:
  1.0   1.0
  5.0   5.0
 10.0  10.0
 10.0  10.0
  5.0   5.0
  1.0   1.0

## a really nice property of projection processes

In [7]:
## associate 𝓘  with its probability
## then associate all j subsets of 𝓘 with that probability over binomial(p,j)
## now add up the probabilities for all j subsets ... that will be the j subset probabilty

In [59]:
k = 3
d = Dict{Array{Int64,1},Float64}()
 for 𝓘 ∈ combinations(1:N, n)
    prob = det(L[𝓘,𝓘]) / binomial(N,n)
    for 𝒬 ∈ combinations(𝓘)
        if haskey(d,𝒬)
            d[𝒬] += prob
        else
            d[𝒬] = prob
        end
    end
end

In [60]:
# the answer that I expect is
for 𝒬 ∈ combinations(1:N)    
      println(𝒬," ",det(L[𝒬,𝒬])/binomial(N,n) ," ", d[𝒬]  ) 
end

[1] 0.004109053880117801 0.004109053880117799
[2] 0.012629645632083072 0.01262964563208307
[3] 0.016915664281013404 0.016915664281013407
[4] 0.005640204372792905 0.005640204372792904
[5] 0.009816393294606582 0.009816393294606585
[6] 0.008945184540538489 0.00894518454053849
[7] 0.01378597025043524 0.013785970250435245
[8] 0.0174435980341268 0.017443598034126803
[1, 2] 0.002141685362348297 0.002141685362348296
[1, 3] 0.003844422960638091 0.0038444229606380887
[1, 4] 0.00022232863351687743 0.00022232863351687678
[1, 5] 0.0022585560395430816 0.0022585560395430807
[1, 6] 0.0015367025051732878 0.0015367025051732865
[1, 7] 0.002456653931885257 0.0024566539318852565
[1, 8] 0.003975866087366314 0.003975866087366312
[2, 3] 0.011712780043281286 0.011712780043281284
[2, 4] 0.0038784871126216615 0.0038784871126216606
[2, 5] 0.005037771427866482 0.0050377714278664835
[2, 6] 0.0059292398878504704 0.005929239887850471
[2, 7] 0.009537157452798928 0.00953715745279893
[2, 8] 0.012281461241565162 0.012281

KeyError: KeyError: key [1, 2, 3, 4, 5, 6] not found

In [10]:
## It seems people prefer to look at this the other way around
## but it amounts to the same thing  (Bayes connection)

## specifically I can generate the n set according to the determinant
## and then the i set uniformly among subsets
## or I can start with the i set and find all the A sets that are supersets

for i = combinations(1:N)
# Generate all subsets Y of length n that contain i
 
 print( sum( det(K[Y,Y]) for Y ∈ combinations(1:N, n) if i ⊆ Y) )
 println( " ",det(K[i,i]) )
end

0.9445495065808777 0.944549506580878
0.9862165653180848 0.9862165653180851
0.8056172107133219 0.8056172107133224
0.12564497229223526 0.1256449722922354
0.38451796185177967 0.38451796185177994
0.5585916165095679 0.5585916165095682
0.24985521920016157 0.24985521920016182
0.9450069475339677 0.9450069475339683
0.9310463676715824 0.9310463676715826
0.7609415711190503 0.7609415711190505
0.11844049534025605 0.11844049534025614
0.3597857291869615 0.3597857291869616
0.5225587025797859 0.5225587025797861
0.19443789474078188 0.19443789474078205
0.8909872656850923 0.8909872656850926
0.7944310661571978 0.7944310661571982
0.12161504277992058 0.12161504277992066
0.37546426483982304 0.37546426483982315
0.5507306529535946 0.5507306529535948
0.23967035992582153 0.23967035992582167
0.9319085069443989 0.9319085069443992
0.051820210532849936 0.05182021053285
0.22669730992164017 0.22669730992164033
0.4306054296062951 0.4306054296062956
0.20114185398682172 0.20114185398682186
0.7568314015294321 0.75683140152

ArgumentError: ArgumentError: reducing over an empty collection is not allowed

## Another identity

In [11]:
det( K[ [1, 2, 3],[1, 2,3]])


0.7499866082671295

In [12]:
sum( det( Y[ [1,2,3],𝒬])^2 for 𝒬 ∈ combinations(1:5,3))

0.7499866082671296

## Now General Λ -- L Ensemble

In [34]:
N,n = 3,3
Y,_ = qr(randn(N,n))
Y = Matrix(Y)
Λ = 10 * Diagonal(rand(n))
L = Y*Λ*Y';

In [35]:
(1 + sum( det(L[𝒬,𝒬]) for 𝒬 ∈ combinations(1:N)))/det(I+L)

1.0000000000000002

## The simple thing:
   Take 𝒬 in the power set of 1:N with probabilty det(L[𝒬;𝒬])/det(I+L)

## Slightly more complicated:
   If A is the power set of 1:N, the probability that A ⊆ 𝒬 is det(K[A;A])

what does this mean?
   This means that if we add up all the disjoint situations of the probability of 𝒬 as above but only when A ⊆ 𝒬, we will get det(K[A;A])
   
   
   Let's take an example : A ={1}
   What we are going to do is take a random subset of 1:N, and we are wondering what is the probablity that we will see a {1} in this subset.  This probablity is K[1,1].
   This is the sum of P[1] +P[1,2] +P[1,3] + P[1,2,4,5] + lots of other things
   
  what is the probabilty of 𝒬 = [1] itself?
Answer: it's the probability that [1] shows up , but without any friends.
    it's not K[1;1]. Remember K[1,1] is the probablity that 1 shows up in 𝒬, usually with friends.  




In [36]:
println("True Probabilities L form")
println("[]"," ",1/det(I+L))
for 𝒬 ∈ combinations(1:N)
    println(𝒬," ",det(L[𝒬,𝒬])/det(I+L))
end

println()
K = L/(L+I) # L * inv(L+I)
# L = K/(I-K)

println("Cumulatives Probabilities K form")
  println("[] ",1)
for A = combinations(1:N)
# Generate all subsets Y
  
 print(A, " ",sum( det(L[Y,Y]) for Y ∈ combinations(1:N) if A ⊆ Y) / det(I+L))
 println(" ",det(K[A,A]) )
end
                

True Probabilities L form
[] 0.025145121174496573
[1] 0.027268114030146094
[2] 0.12258605519952914
[3] 0.072843135488256
[1, 2] 0.10400630157178155
[1, 3] 0.06842918277873793
[2, 3] 0.3503444063036518
[1, 2, 3] 0.22937768345340095

Cumulatives Probabilities K form
[] 1
[1] 0.4290812818340666 0.4290812818340665
[2] 0.8063144465283635 0.8063144465283634
[3] 0.7209944080240467 0.7209944080240467
[1, 2] 0.3333839850251825 0.33338398502518246
[1, 3] 0.29780686623213887 0.2978068662321389
[2, 3] 0.5797220897570527 0.5797220897570527
[1, 2, 3] 0.22937768345340095 0.22937768345340098


In [51]:
println("True Probabilities L form")
println("[]"," ",1/det(I+L))
for 𝒬 ∈ combinations(1:N)
    println(𝒬," ",det(L[𝒬,𝒬])/det(I+L))
end

println()
K = L/(L+I) # L * inv(L+I)
# L = K/(I-K)

println("Cumulative Probabilities K form")
  println("[] ",1)
for A = combinations(1:N)
# Generate all subsets Y
  
 print(A, " ",sum( det(L[Y,Y]) for Y ∈ combinations(1:N) if A ⊆ Y) / det(I+L))
 println(" ",det(K[A,A]) ," ",det( (I-K)[A,A]))
end

True Probabilities L form
[] 0.25
[1] 0.23650321903325422
[2] 0.08462898164818665
[3] 0.17886779931855912
[1, 2] 0.07113220068144088
[1, 3] 0.16537101835181334
[2, 3] 0.013496780966745756
[1, 2, 3] 0.0

Cumulative Probabilities K form
[] 1
[1] 0.47300643806650844 0.4730064380665084 0.5269935619334916
[2] 0.1692579632963733 0.1692579632963733 0.8307420367036267
[3] 0.35773559863711824 0.3577355986371182 0.6422644013628818
[1, 2] 0.07113220068144088 0.07113220068144087 0.4288677993185591
[1, 3] 0.16537101835181334 0.16537101835181328 0.33462898164818666
[2, 3] 0.013496780966745756 0.013496780966745763 0.48650321903325416
[1, 2, 3] 0.0 -9.030968264314201e-18 0.24999999999999997


In [43]:
## an n-DPP becomes a full DPP

In [73]:
N,n = 6,3
Y,_ = qr(randn(N,n))
Y = Matrix(Y)
L = Y*Y'

6×6 Array{Float64,2}:
  0.384423   -0.364608    0.209507   0.171558   0.150765    0.0874502
 -0.364608    0.6224     -0.126582   0.198084   0.0829244  -0.199857 
  0.209507   -0.126582    0.516244   0.181959  -0.166938   -0.358947 
  0.171558    0.198084    0.181959   0.547297   0.366508   -0.107964 
  0.150765    0.0829244  -0.166938   0.366508   0.491209    0.24108  
  0.0874502  -0.199857   -0.358947  -0.107964   0.24108     0.438427 

In [74]:
# This is a probability space
z=0
 for 𝒬 ∈ combinations(1:N,n)
     z += det(L[𝒬,𝒬])
    println(𝒬," ",det(L[𝒬,𝒬]))
end
println(z)

[1, 2, 3] 0.0407501053959993
[1, 2, 4] 8.778652896906332e-6
[1, 2, 5] 0.026320797765855566
[1, 2, 6] 0.03924630100088385
[1, 3, 4] 0.06974992132308963
[1, 3, 5] 0.042929271455824806
[1, 3, 6] 0.0011336138794220663
[1, 4, 5] 0.043770282155239044
[1, 4, 6] 0.06743234314848147
[1, 5, 6] 0.053081484394358086
[2, 3, 4] 0.11709497032648515
[2, 3, 5] 0.1325695214850944
[2, 3, 6] 0.01487284518105414
[2, 4, 5] 0.07272169617124641
[2, 4, 6] 0.1115747982449965
[2, 5, 6] 0.06724008904984066
[3, 4, 5] 0.01565792641488555
[3, 4, 6] 0.046927129151012166
[3, 5, 6] 0.03455910465213182
[4, 5, 6] 0.0023590201512014345
0.9999999999999991


In [85]:
# For every subset of 1:N add up the probabilities that are included
for Y ∈ combinations(1:N)
    print(Y)
    zz = sum( det(L[union(Y,T),union(Y,T)]) for T ∈ combinations( setdiff(1:N,Y), n-length(Y)) )
    print(" ",zz),println(" ",det(L[Y,Y]))
end

[1] 0.38442289917205075 0.38442289917205086
[2] 0.6223999032743529 0.6223999032743532
[3] 0.5162444092649991 0.5162444092649996
[4] 0.5472968657395344 0.5472968657395347
[5] 0.49120919369567784 0.49120919369567817
[6] 0.43842672885338213 0.4384267288533825
[1, 2] 0.10632598281563563 0.10632598281563563
[1, 3] 0.1545629120543358 0.15456291205433584
[1, 4] 0.18096132527970704 0.18096132527970707
[1, 5] 0.1661018357712775 0.16610183577127755
[1, 6] 0.16089374242314552 0.16089374242314552
[2, 3] 0.305287442388633 0.30528744238863315
[2, 4] 0.301400243395625 0.30140024339562504
[2, 5] 0.29885210447203703 0.2988521044720371
[2, 6] 0.2329340334767751 0.23293403347677524
[3, 4] 0.24942994721547251 0.24942994721547274
[3, 5] 0.22571582400793658 0.22571582400793674
[3, 6] 0.09749269286362022 0.09749269286362026
[4, 5] 0.13450892489257243 0.13450892489257255
[4, 6] 0.22829329069569157 0.22829329069569168
[5, 6] 0.15723969824753203 0.1572396982475321
[1, 2, 3] 0.0407501053959993 0.0407501053959993

ArgumentError: ArgumentError: reducing over an empty collection is not allowed

In [78]:
?setdiff

search: setdiff setdiff! selectdim setrounding searchsortedfirst



```
setdiff(s, itrs...)
```

Construct the set of elements in `s` but not in any of the iterables in `itrs`. Maintain order with arrays.

# Examples

```jldoctest
julia> setdiff([1,2,3], [3,4,5])
2-element Array{Int64,1}:
 1
 2
```


In [71]:
?issubset

search: issubset



```
issubset(a, b)
⊆(a,b)  -> Bool
⊇(b, a) -> Bool
```

Determine whether every element of `a` is also in `b`, using [`in`](@ref).

# Examples

```jldoctest
julia> issubset([1, 2], [1, 2, 3])
true

julia> [1, 2, 3] ⊆ [1, 2]
false

julia> [1, 2, 3] ⊇ [1, 2]
true
```
