In [135]:
using LinearAlgebra, Combinatorics, StatsBase

In [153]:
function lis_mc(k,t=100_000)
# k is the permutation size
 c = zeros(k)
 v = zeros(t)
 for j=1:k
   for i=1:t
    U, = qr(randn(j,j)+im*randn(j,j)) # random jxj unitary matrix with Haar measure
    U *= Diagonal([exp(2*π*im*rand()) for i = 1:j])
    v[i]= (abs(tr(U)))^(2k)
   end
 c[j]=sum(v)/length(v) 
 end
 return c
end

lis_mc (generic function with 2 methods)

In [128]:
function patiencesort(p)
    # p : Permutation
    # Returns length of longest increasing subsequence
    pile_tops = Int[]
    for α ∈ p       
        whichpile = 1+sum(α.>pile_tops) # first pile where α is smaller
        if  whichpile ≤ length(pile_tops)
            pile_tops[whichpile] = α   # put α on top of a pile  or ..
        else
            push!(pile_tops, α)        # create a new pile
        end
    end
    return length(pile_tops)
end

patiencesort (generic function with 1 method)

In [168]:
function lis_theory(k)
    # exactly counts permutations with lis ≤ j for j=1,2,...,k
    lis = [patiencesort(π) for π ∈ permutations(1:k)]
    [sum(lis.≤j) for j=1:k]
end

lis_theory (generic function with 1 method)

In [160]:
[ lis_mc(3) lis_theory(3)]

3×2 Array{Float64,2}:
 1.0      1.0
 4.96271  5.0
 6.0351   6.0

In [162]:
[ lis_mc(4,1000000) lis_theory(4)]

4×2 Array{Float64,2}:
  1.0      1.0
 13.9712  14.0
 22.9554  23.0
 24.3682  24.0

In [169]:
[ lis_mc(5,1_000_000) lis_theory(5)]

5×2 Array{Float64,2}:
   1.0       1.0
  41.8781   42.0
 103.345   103.0
 119.422   119.0
 120.043   120.0